dist: bionic
language: minimal
sudo: required

services:
  - docker

before_install:
  - curl -fsSL https://goss.rocks/install | sudo sh

script:
  - export COMMIT_RANGE="${TRAVIS_COMMIT_RANGE:-}"
  - make auto
