name = "SnapServ: VirtuSky"
min_version = "0.41"

[author]
  name = "Pascal Mathis"
  homepage = "https://pascalmathis.com"

[original]
  name = "VirtuSky by themelooks"
  homepage = "https://themeforest.net/item/virtusky-responsive-web-hosting-and-whmcs-wordpress-theme/20499450"
