[entryPoints]
  [entryPoints.web]
    address = ":8080"
  [entryPoints.web-secure]
    address = ":8443"
  [entryPoints.ping]
    address = ":8081"

[ping]
  entryPoint = "ping"

[providers]
  [providers.file]
    directory = "/cts/traefik/config"
    watch = true
